on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: postgresql-patroni
  POSTGRES_VERSION: ${{ vars.POSTGRES_VERSION }}

jobs:
  build:
    name: Deploy to ghcr.io
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Build
      run: | 
        ./build.sh
    - name: Push image to GitHub - master
      if: ${{ github.ref_name == 'master' }}
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
        docker tag postgresql-patroni ghcr.io/${{github.repository_owner}}/${{env.IMAGE_NAME}}:${{env.POSTGRES_VERSION}}
        docker push ghcr.io/${{github.repository_owner}}/${{env.IMAGE_NAME}}:${{env.POSTGRES_VERSION}}

